import Head from 'next/head';
import { Container } from '@chakra-ui/react';
import Navbar from '@src/components/Navbar';

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <main>
        <Container maxW='container.xl'>{children}</Container>
      </main>
    </>
  );
}
